#Variables APIRest
server:
  servlet:
    context-path: /apirest
  port: 8086

#Conexion Base de Datos
#spring.datasource.url=jdbc:sqlserver://certusprofesores.database.windows.net:1433;database=marketplace;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.username=jflorese
#spring.datasource.password=James.05

#Configuracion de persistencia

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServer2016Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
##spring.datasource.dbcp2.validation-query=select 1 from dual

#Conexion Base de Datos
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #Configuracion de persistencia
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  dbcp2:
    validation-query: select 1 from dual