#Variables APIRest
server:
  servlet:
    context-path: /apirest
  port: 8085

spring:
  cloud:
    config:
      profile: users

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

  #Configuracion de persistencia
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  dbcp2:
    validation-query: select 1 from dual